name: Debian

on: [push]

jobs:
  build:
    name: Build for ${{ matrix.arch }} / ${{ matrix.debian-version }}

    # docker executor
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64]
        debian-version: [buster]

    container:
      image: ${{ matrix.arch }}/debian:${{ matrix.debian-version }}-slim
      env:
        DEBIAN_FRONTEND: noninteractive

    steps:
    - uses: actions/checkout@v1

    - name: Install build dependencies for Linux daemon 'callblockerd'
      run: |
        apt-get update
        apt-get install --no-install-recommends -y \
          debhelper build-essential \
          dpkg-dev pkg-config \
          ninja-build meson \
          python3-pip python3-setuptools python3-wheel \
          g++ gcc \
          libjson-c-dev libphonenumber-dev uuid-dev libssl-dev
        pip3 install meson
        meson -v
        whereis meson

    - name: Install build dependencies for web-interface
      run: |
        apt-get install --no-install-recommends -y \
          ca-certificates wget
        wget -qO- https://deb.nodesource.com/setup_12.x | bash -
        apt-get update
        apt-get install --no-install-recommends -y \
          nodejs

    - name: Build package
      run: |
        export PATH=/usr/local/bin:$PATH
        dpkg-buildpackage -b -uc
        mkdir -p artifacts
        cp ../callblocker_* artifacts

    - name: Archive Debian package artifacts
      uses: actions/upload-artifact@v1
      with:
        name: debian
        path: artifacts

